version: '3'
services:

  ip2tor-host:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: ip2tor-host
    hostname: ip2tor-host
    volumes:
      - .:/home/ip2tor
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "21212-21221:21212-21221"
    networks:
      - hostnet
networks:
    hostnet:
        driver: bridge
