version: '3'
services:

  ip2tor-host:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        HOST_IP: ${IP2TOR_HOST_IP}
    container_name: ip2tor-host
    volumes:
      - .:/home/ip2tor
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    network_mode: "host"